## 예외
이 **예외** 처리라는 말이 조금 오해를 일으킬 수 있음
- 예측 못하고 마주하는 문제 => **오류**
- **예외**는, 문제가 발생할 것을 이미 알고 있는 경우
예외가 발생할 수 있다고, 위험함을 알리고 싶으면,
- 함수 작성 시 `public static int func() throws Exception` 이런식으로 `throws Exception`을 쓴다!
	=> 그럼 그냥 쓸 수 없음
- 함수 사용 시 `try {func()}catch (Exception e) {}` 이런식으로 쓴다
- 함수에서 exception을 `throw`하는 경우, 그대로 함수는 끝나고 `catch(Exception e) {}` 부분으로 넘어간다
- `Exception`은 클래스임. 
- `catch (Exception a)`에 대해, `e.printStackTrace` => 정보와 에러를 띄워준다. 띄우고 끝내진 않음. 그럴거면 `System.exit(-1)` 추가
- try문 안에 exception throw하는 함수가 여러 개 있어도 무관함
	- 필요한 catch문을 전부 추가하기만 하면 됨 아래와 같이
```java
try {
	func1();
	func2();
	func3();
	func4();
} catch (Exception1 e) {

} catch (Exception2 e) {

} catch (Exception3 e) {

} catch (Exception4 e) {

}
//구조적 예외처리. 각기 모두 다른 Exception을 가져도 무관, catch만 하면 됨
```
- **부모 Exception이 위에 있으면 안됨** . 순서가 중요
	- 구체적인게 위로, 포괄적인게 밑으로
	- 포괄적인게 위에 있으면 다 가져가버리니까
- ++ `finally` : try-catch문을 전부 수행하고 무조건 여기를 지난다
	- try에서 문제가 없었어도, 또는 문제가 생겨서 catch로 넘어갔어도, 무조건 `finally`문을 지난다
- 특정 Exception을 던지는 위험한 함수를 쓰는 함수의 경우, try-catch를 통해 이를 해결할 수도 있지만, 이걸 다시 던질 수도 있다 => 미룬다
	- 같은 종류의 Exception을 throw하도록 작성
- 0으로 나누는 연산, 또는 OutOfIndex 연산 등은 "위험"하지만 try-catch없이 사용할 수는 있도록 "약속"되어있음
	- /, Array, null-pointer, type casting, 등..
	- 너무 자주 쓰는 기능이라, 매번 try-catch로 묶지 않아도 됨 (굳이)
- 위와 같은 약속된 경우를 => **UncheckedException**, or **RuntimeException** 이라고 함
- 반면 꼭 try-catch로 묶어야 하는 경우를 **CheckedException**  (Error와 RuntimeException 제외한 나머지)

----
여기까지 시험범위 